application: tesorio-company
version: 2
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- django_wsgi: on


handlers:
- url: /favicon\.ico
  static_files: tesorio/favicon.ico
  upload: favicon\.ico

- url: /robot.txt
  static_files: media/robot.txt
  upload: media/robot.txt

# Static folders
- url: /media
  static_dir: tesorio/media/
  secure: optional

- url: .*
  script: main.app

- url: /_ah/devcon/.*
  script: google.appengine.ext.admin.application
  login: admin

libraries:
- name: jinja2
  version: "latest"
- name: django
  version: 1.5
- name: lxml
  version: 2.3
- name: pycrypto
  version: "latest"